### ISSUE TITLE
Support multiple gamemodes at once

### ISSUE THREAD

**Issue by trundler-dev** [trundler-dev/sbox-sports#15]
We should have a List of Gamemode entities on the game class, iterate on them, and the participants of each gamemode instance. 

Considerations: 
- Can multiple people play different instances of the same gamemode at once?
- Level streaming concerns (no vis)

**Acceptance Criteria**
- Game supports multiple gamemodes
- A basic design is documented somewhere

**Comment by DevulTj** [comment]
**Can multiple people play different instances of the same gamemode at once?**
Yes, if we wanted to.

**Game supports multiple gamemodes**
This is work in progress on `feature/gamemode-system` branch. I'm probably gonna get @DoctorGurke to review it when it's ready.

**Player Journey (Design)**
- Player joins game, is given a default Pawn which is just a third person dude with their cosmetics on, they can run around some lobby area.
- Orbs around the lobby map with gamemode status, showing who's in a gamemode etc.
- When interacting with the orb, you can choose to join the game.
- When the game starts, your gamemode's logic is self contained, and your player is assigned to a new Pawn. It can be based off the default Pawn we provide, or be something **entirely different.** The choice is yours.
- Gamemodes also specify a panel for a gamemode specific HUD.
- You can leave a gamemode at any point.
- When you disconnect, you are treated as leaving the gamemode.

**Comment by DevulTj** [comment]
Implemented.
