### ISSUE TITLE
Add bowling pin entity

### ISSUE THREAD

**Issue by trundler-dev** [trundler-dev/sbox-sports#23]
Now that we have bowling pin models in, we can add the pin entity in!

**Acceptance Criteria**
- Bowling pin entity added
- Physics exist and make sense

**Comment by DoctorGurke** [comment]
I haven't done much manual physics in sbox yet, but with pins it's sort of important that the shape and mass act properly, so I'm not sure how exactly that'd work with predicted physics. Any insights @xezno?

**Comment by xezno** [comment]
I think we can set up the pins with keyframed physics and do traces against those, then do custom logic to get them to act how we want

**Comment by xezno** [comment]
I could probably take a look at this tomorrow if you want

**Comment by trundler-dev** [comment]
A bowling pin entity has been created, closing this.
