### ISSUE TITLE
Add simple BowlingPlayer entity

### ISSUE THREAD

**Issue by trundler-dev** [trundler-dev/sbox-sports#3]
In order to support multiple games, we should organize our code folder appropriately.

`code/gamemodes/<sport_name>` - root folder for each sport
`code/libs` - game-unspecific libraries

Let's create a folder for bowling, and add our BowlingPlayer class. Give it a basic setup. Temporarily hook it up to the game class, assign the Pawn, etc on ClientJoined. We will delegate this task to another class in the future, to make swapping pawns versatile.

**Acceptance Criteria**
- BowlingPlayer is added with a basic setup
- client.Pawn is set to BowlingPlayer in ClientJoined
- Files belong in their proper folders

**Comment by DevulTj** [comment]
I think they should be referred to as GameModes instead of Sports, as Sports is the game's name.

**Comment by ShadowBrian** [comment]
We should also figure out how clothing is going to be handled- some gamemodes (like bowling) will only replace part of the wardrobe if any, others might be more invasive about it.

Bowling could have bowling shoes but not sure it should have more than that

**Comment by DoctorGurke** [comment]
the gamemodes can just override pawn respawn and do whatever they want with the pawn, ie attach clothes etc

**Comment by xezno** [comment]
Addresed in #47
