### ISSUE TITLE
Add Gamemode Orb Artist Features

### ISSUE THREAD

**Issue by GunnarKafel** [trundler-dev/sbox-sports#35]
- [x] Convert to a trigger to better control collision area
- [x] Particle property
- [x] VSnap file & mesh KVs

Main reason for switching over to triggers & particles is so I can make abstract entrances for the gamemodes
![image](https://user-images.githubusercontent.com/65134886/169185009-6bd07984-cc3a-4b30-82db-6dac49fb35fe.png)

**Comment by DevulTj** [comment]
It's already a trigger, but it's not customizable in size. I will add a property for it to be modifiable.

**Comment by DevulTj** [comment]
Since I've approved the PR linked to this task, this will also be closed
