### ISSUE TITLE
Investigate Nameplate Stacking

### ISSUE THREAD

**Issue by DevulTj** [trundler-dev/sbox-sports#41]
If there are multiple people with nameplates, it's probably gonna overlap. I already implemented a feature so it'll flip to the other side of a player, but there's no other behavior for if **that** side is also occupied.

**Comment by trundler-dev** [comment]
Just experimenting with nameplates, I don't really see this as an issue. Even with players grouped up tightly, it feels pretty natural to move the camera a tiny bit so you can see the nameplate. I'll leave it open if you guys think differently, but I'd be happy to close it.

**Comment by DevulTj** [comment]
we'll kill it for now and raise this if it ever becomes a **real problem live.**
