### ISSUE TITLE
Implement the bowling game flow

### ISSUE THREAD

**Issue by trundler-dev** [trundler-dev/sbox-sports#48]
We need a system for controlling flow (or state) of a bowling instance.

The following functionality should exist:
- A state of waiting, where the host can start the game whenever all the desired players are in.
- A state of playing, where players (and AI, if applicable) take turns playing. Should also work flawlessly with a single player.
- An end state, after all turns have completed. Players should be allowed to return to a waiting state, or return to lobby. If the host of the instance leaves, a new host is selected.

**Comment by Adesii** [comment]
this should probably be generic. so we can reuse it for other gamemodes.
so basically a statemachine.
